server:
  port: 8085

spring:
  application:
    name: loyalty-service
  datasource:
    url: ${LOYALTY_DB_URL}
    username: ${LOYALTY_DB_USER}
    password: ${LOYALTY_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

gateway:
  internal-secret: ${GATEWAY_INTERNAL_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
