server:
  port: 8083

spring:
  application:
    name: payment-service
  datasource:
    url: ${PAYMENT_DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

gateway:
  internal-secret: ${GATEWAY_INTERNAL_SECRET}

loyalty:
  base-url: ${LOYALTY_SERVICE_URL:http://localhost:8085}
  connect-timeout-ms: 2000
  read-timeout-ms: 3000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
